version: '3'

services:
  zerkel:
    image: zerkel
    build:
      context: '.'
      dockerfile: src/Dockerfile
    ports:
      - "8888:8888"
  
  zerkel-doc:
    image: zerkel-doc
    build:
      context: '.'
      dockerfile: docs/Dockerfile
    ports:
      - "8080:8080"
